services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d:ro
    networks:
      - backend
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: '0'
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis-config:/usr/local/etc/redis:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
    driver: bridge

