services:
  mysql:
    image: mysql:8.2
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d:ro
    networks:
      - backend
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: '0'
      UPLOAD_LIMIT: 64M
      MAX_EXECUTION_TIME: 600
      # PMA_ABSOLUTE_URI: http://localhost:8080/
      # PMA_CONFIG_BASE64: true
      # PMA_USER_CONFIG_BASE64: true
      # PMA_SAVE_ON_PASSWORD: false
      # PMA_ALLOW_EMPTY_PASSWORD: false
      PMA_QUERYHISTORY_MAX: 100
      PMA_QUERYHISTORYDB: true
      PMA_SERVER: mysql
      PMA_SSL: false
      PMA_COOKIE_SECURE: false
      PMA_COOKIE_HTTPONLY: true
      PMA_COOKIE_SAMESITE: None
      PMA_HOSTS: mysql:3306
      PMA_SERVER_HOST: mysql
      PMA_SERVER_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "mysql:172.20.0.2"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis-config:/usr/local/etc/redis:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

